name: Catch and Flow

on:
  push:
    paths:
      - 'src/**'
      - 'roulette_macros/**'
      - 'test/**'
      - 'Cargo.lock'
    branches: [ 'feature/*' ]
  pull_request:
    branches: [ develop, master ]

jobs:
  clippy_check:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: LoliGothick/clippy-check@v0.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow: >
            nonstandard_macro_braces
            mutex_atomic
          deny: warnings

  rustfmt_check:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - uses: LoliGothick/rustfmt-check@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          flags: --all
          args: --config-path=rustfmt_for_actions.toml

  test:
    name: Run Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          rustup update nightly
          rustup default nightly
          cargo +nightly test -j11 --release --all-features
