name: Catch and Flow

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Cargo.lock'
    branches: [ 'feature/*', 'master' ]

jobs:
  clippy_check:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --deny warnings

  rustfmt_check:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - name: test
        run: cargo fmt --check

  test:
    name: Run Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          rustup update nightly
          rustup default nightly
          cargo +nightly test -j11 --release --all-features
